---
# tasks file for ec2
- name: Set Python interpreter
  set_fact:
      ansible_python_interpreter: "/home/ubuntu/myenv/bin/python"
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
      name: "ansible-instance"
      key_name: "vpckey"
      vpc_subnet_id: subnet-0af529be0edf8ff8f
      instance_type: "{{ type }}"
      security_group: sg-0f357eb40e1bcf32d
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
      network:
        assign_public_ip: true
      image_id: ami-0e86e20dae9224db8

